### ISSUE TITLE
Error loading teams and unboxing chat messages.

### ISSUE THREAD

**Issue by x-kej** [keybase/client#10272]
I believe this is the same issue as #9627, even down to happening after an account reset involving co-owned teams.

After the account reset, I logged in with my personal laptop, and then connected my android phone and my work laptop. The error does **not** occur on the personal laptop, but consistently occurs on both the phone and the work laptop.

my log id: 642e48a84078ae0dab71b51c

**Comment by stresler** [comment]
I can confirm I'm seeing this on Android 6.0.1. This is the same, worked before I did a full key reset, not after. 

Another maybe-useful note is that I don't seem to have the issue with new chats, just ones from followers (or maybe team members) I had before the reset? 

Same as with #9627, I had to be re-added to the team.

Specific error message I get is, "error unboxing chat message: appendix 4->5: Implicit team operation not allowed: team."

Everything works as expected on laptop (xubuntu/ubuntu 14.04LTS).

**Comment by stresler** [comment]
So, I uninstalled and re-installed keybase on my phone. Upon initially opening the app, I scan the QR code, and get: 

"Error Code 218: multiple errors while loading team list in method keybase.1.teams.teamList", with a long list of errors, which I can't screenshot due to the nice security. 

Closing out of that, I am now getting an 'error unboxing chat messages: Not found' with all chats related to the only team I'm on, both individual chats of people on that team, and team chats. But not with individual chats with people not on that team.

**Comment by maxtaco** [comment]
We fixed this bug but haven't release it yet.

For now: hamburger > advanced > DB Nuke

should fix it, LMK if not....

**Comment by crunchywelch** [comment]
I'm the other user interacting with stresler and seeing the same errors / issues in the chat with him from my side as well. I've submitted my logs a moment ago, in the state prior to any db nuke. I've since nuked my db and am getting `error unboxing chat message: append-ing 4->5: Implicit team operation not allowed: team.invited`
Additional information that may be useful or not: I created a team and invited stresler to it, and that team chat is working, it is only dm that is not. I am also able to dm properly with other users, and with users on the same team. DM between stresler and myself works on desktop.

Let me know if I can help debug in any other ways, or provide additional information.

**Comment by x-kej** [comment]
DB Nuke seems to have worked on the phone, but the advanced menu item appears to be missing from the Windows client.

**Comment by crunchywelch** [comment]
@x-kej make sure you have the most recent client, the nuke db button was added relatively recently. Or you can do it from the command line...

**Comment by maxtaco** [comment]
On Windows/macOS/Linux, use `keybase db nuke`

**Comment by x-kej** [comment]
@maxtaco that did the trick, thank you.

**Comment by mmaxim** [comment]
This whole thing should be fixed in the latest release on the desktop and mobile apps. Android just went out yesterday, so if you haven't had a chance to grab the update, it should make all this better.

**Comment by stresler** [comment]
This has been fixed on Android. Thanks!

**Comment by xibxor** [comment]
This issue still isn't fixed on desktop. When is release going out?

**Comment by mlsteele** [comment]
@xibxor log send please?

**Comment by xibxor** [comment]
The issue persists on newest Android as well. I'm trying to message a friend (not a team) and it says "Error: You are not a member of this team." I will have to reinstall to get the logs, I do not have them right now.

**Comment by mlsteele** [comment]
If you reset your account then you are basically out of the team. One of the admins would have to let the new you back in.

**Comment by xibxor** [comment]
There was never a team. Private messages is all I use.

**Comment by mmaxim** [comment]
Yeah this is an instance of an implicit team getting reset before a chat was made. @xibxor, if you feel comfortable you can PM me the name of the conversation on Keybase chat and I can manually fix it for you.

**Comment by xibxor** [comment]
I appreciate the offer @mmaxim. I'm more interested in a permanent fix, as many users who are non-developers might be experiencing similar difficulties. I'm willing to donate time to write a patch. But could you point me to the network code / relevant code for this implicit team construct? Thanks

**Comment by mmaxim** [comment]
@xibxor this might be fixed for you now, although could you send a log if you get a chance so we can see the problem?
