### ISSUE TITLE
keybase chat ls causes panic

### ISSUE THREAD

**Issue by tdons** [keybase/client#10445]
```
$ keybase chat ls
panic: wrong case accessed

goroutine 1 [running]:
github.com/keybase/client/go/protocol/chat1.MessageSystem.Addedtoteam(0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/build/go/src/github.com/keybase/client/go/protocol/chat1/local.go:287 +0x9c
github.com/keybase/client/go/client.formatSystemMessage(0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_cli_rendering.go:436 +0x25a
github.com/keybase/client/go/client.newMessageViewValid(0xc42017b180, 0xc42020a300, 0x20, 0x20, 0xc42012e490, 0x10, 0x10, 0x1, 0xc42012e4a0, 0x10, ...)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_cli_rendering.go:512 +0xbe6
github.com/keybase/client/go/client.newMessageView(0xc42017b180, 0xc42020a300, 0x20, 0x20, 0x1, 0xc420119800, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_cli_rendering.go:623 +0x303
github.com/keybase/client/go/client.conversationListView.show(0xc4200b5600, 0x5, 0x5, 0xc42017b180, 0xc4202796d8, 0x5, 0xc42023f400, 0x3, 0x4)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_cli_rendering.go:219 +0x372
github.com/keybase/client/go/client.(*cmdChatList).Run(0xc42011e980, 0xc420264540, 0x5e10af0)
	/Users/build/go/src/github.com/keybase/client/go/client/cmd_chat_list.go:42 +0x13e
main.mainInner(0xc42017b180, 0x0, 0x0)
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:159 +0x71b
main.main()
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:64 +0xa6
```
my log id: 164ce2b8932c629279ad641c

**Comment by maxtaco** [comment]
cc @patrickxb --- thought we solved this one?

**Comment by maxtaco** [comment]
Oh, the call to `SystemType` is probably erroring and we're not looking at the error.

**Comment by patrickxb** [comment]
Yeah, we should check that error.

**Comment by patrickxb** [comment]
Fixed here:  https://github.com/keybase/client/pull/10463

**Comment by fladd** [comment]
I have the same issue. Tried updating Keybase (by downloading the macos installer again and reinstalling), but the issue remains.

**Comment by maxtaco** [comment]
Fix is in master but not yet released
