### ISSUE TITLE
Keybase errors in a relatively new team

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#13737]
Got this error: Error: ERROR CODE 218 - error unboxing chat message (transient): fast load error: team chain doesn't have a link for seqno 3, but expected one in method chat.1.local.getThreadNonblock at new r (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:467262) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:467791 at d (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:467830) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:412593) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2669974 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2373434) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2373585 at r (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2373214) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2373544) at r (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2372748)

my log id: fa1276873991301600cc651c

**Comment by RyanSinger** [comment]
Can't send messages to that team anymore

**Comment by RyanSinger** [comment]
![image](https://user-images.githubusercontent.com/2665386/45506543-6716b280-b744-11e8-8289-91ef5362c5be.png)

**Comment by maxtaco** [comment]
On it, sorry about the bug.

**Comment by RyanSinger** [comment]
Didn't work. See d589b9f78d729c8b0d75c41c

![screenshot 2018-09-13 at 11 29 13 am](https://user-images.githubusercontent.com/2665386/45507964-58ca9580-b748-11e8-8c09-3ee8d338eb54.png)

**Comment by maxtaco** [comment]
Hmm, ok try a `keybase db nuke` and then try again?

**Comment by maxtaco** [comment]
Or if not that, can you click the team in the teams tab?

**Comment by maxtaco** [comment]
OK, we have a fix up: https://github.com/keybase/client/pull/13739

We have a new "auditor" feature that randomly probes the merkle tree to make sure the server isn't trying to fork a team.  It didn't work against a stale cached team. Your view of marketing is cached, and you haven't had a need to bust that cache. I think reloading team from team tab in the GUI would be enough.  I thought `list-memberships` would, but I guess not. We had some small downtime yesterday too so you might also have missed a cache invalidation pushed from the server.

**Comment by maxtaco** [comment]
@RyanSinger LMK if the workaround worked. I'd like to get a test in with the PR but we can force out a push if we have to.

**Comment by maxtaco** [comment]
Should be fixed in next Linux release. Reopen if not. Thanks.

**Comment by stephthegeek** [comment]
I'm in the same team still having issues after running those commands. See screenshot: https://drive.google.com/file/d/1cW4JCVFOVO5BquZ5WfpfZa9ZPC16ZPGY/view?usp=sharing

Just submitted log id ea608df3acc33ec899538a1c

**Comment by maxtaco** [comment]
The issue is that a writers should be allowed to create KBFS shares, but our team player seems to be disallowing that. @stephthegeek it seems like you created the KBFS share for this team, after you were let in as a writer. We're considering 3 options: (1) relax the rules on the client; (2) kill this team; or (3) special case this link.  I'm leaning toward (1), but @mlsteele and I will mull it over.

**Comment by maxtaco** [comment]
Ok, fix is in master here: https://github.com/keybase/client/pull/13755

Question: can you guys wait 3 weeks on a release for this, or is it crucial, in which case we can (1) do a global hotfix; or (2) give you a daily (via the 'admin' channel).

Linux build should hopefully go out this afternoon

**Comment by maxtaco** [comment]
Hotfix out! Reopen if still an issue.
