### ISSUE TITLE
Facebook proof fails despite having posted.

### ISSUE THREAD

**Issue by jgentil** [keybase/client#13923]
https://www.facebook.com/zenethian/posts/10155587787267021 is my proof and it never saw it.  I used the app to post this.  It never proofed.  :(

**Comment by jgentil** [comment]
In `keybase id zenethian` I see this:
```
✔ "zenethian" on facebook failed: No server-given hint for sig=c97454b41e5d9f545b044b35e2fdb9c9d2fc5d9feabc6fc2e1d1dddb0c4ea1860f (code=306)
```

**Comment by cereal-s** [comment]
Same here,

when I perform `keybase prove facebook` and paste the given link I get:

    Error 500. Something is not right. We will look into it.

The post is there and it is public: https://www.facebook.com/0x63657265616C/posts/10161006931410381

I have tried multiple times, through browser and command line. Something to take into account: I recently (24h ago) changed my FB id.

**Comment by jgentil** [comment]
Bumping for visibility or at least acknowledgment.

**Comment by linguisten** [comment]
same here

**Comment by mlsteele** [comment]
Fixed see https://github.com/keybase/client/issues/14537#issuecomment-435939898

**Comment by jgentil** [comment]
Still getting a 500 server error on the link back and it fails to validate.
