### ISSUE TITLE
reddit proof fails

### ISSUE THREAD

**Issue by prmam** [keybase/client#14153]
https://www.reddit.com/r/KeybaseProofs/comments/9lidhw/my_keybase_proof_redditzsjr_keybaseprmam/

I noticed that there is a minor difference in the html that is generated in the "I am" section. Others have rel="nofollow" in the link markup for each identity, but I don't. I have no idea if this has any impact on the validity of the proof.

It does not appear that the "I fixed it - recheck" button in the UI has any action behind it. I would expect the status to change from "unreachable" to something different.

    $ keybase version
    Client:  2.7.0-20180926133747+0d62c866fc
    Service: 2.7.0-20180926133747+0d62c866fc

**Comment by aubergene** [comment]
I found that posting to https://**old**.reddit.com worked, the new site doesn't seem to be compatible

**Comment by prmam** [comment]
> I found that posting to https://**old**.reddit.com worked, the new site doesn't seem to be compatible

Thank you. That seems to have solved the matter using the original data.

**Comment by prmam** [comment]
> Try upgrading your app

Stating that an upgrade to the app is necessary without providing context is not very helpful. Telling us, "The problem has been identified and is corrected in version X.Y.Z which was released on ccyyMONdd" is much more useful.

**Comment by markblundeberg** [comment]
I had two problems:

* First, the proof body did not appear at all since the reddit editor was in 'fancy pants mode'.
* Next, the proof posted in full but *still* failed to verify: [here](https://www.reddit.com/r/KeybaseProofs/comments/9tzoob/my_keybase_proof_redditmarkblundeberg/)

Finally I modified the prefill URL to point to **old**.reddit.com and it succeeded: [here](https://www.reddit.com/r/KeybaseProofs/comments/9uy9ni/my_keybase_proof_redditmarkblundeberg/). I have *no* idea what is the difference.

(note: I generated all proofs via the gpg+curl command line route)

**Comment by Ultrabenosaurus** [comment]
This is still a problem. I tried @markblundeberg's old.reddit.com trick and the post now has body text, but Keybase still can't find it. The website shows the post link in red with "replace" and "abandon" as options while the Windows 10 app says "unreachable" and gives me a retry option, but nothing visually happens when I click it.

**Comment by iamnewton** [comment]
I'm having the same issue with Reddit as well. Its [here](https://www.reddit.com/r/KeybaseProofs/comments/9xuu2j/my_keybase_proof_redditchrisopedia/).

**Comment by t-bast** [comment]
Same for me, the Reddit proof fails to verify.
My proof is [here](https://www.reddit.com/r/KeybaseProofs/comments/a0ht38/my_keybase_proof_redditbast42_keybasetbast/).
