### ISSUE TITLE
OSX Finder setup doesn't work

### ISSUE THREAD

**Issue by danielbressan** [keybase/client#14689]
Open new issue on request from @strib  
Similar to a few older closed issues I can get the client to load, but it will not mount so I can view files in finder:
https://github.com/keybase/client/issues/8888
https://github.com/keybase/kbfs/issues/1360

I get this error when starting up keybase on High Sierra 10.13.6 on client bootup:

> We were unable to load KBFS (Fuse kext). This may be due to a limitation in MacOS where there aren't any device slots available. Device slots can be taken up by apps such as VMWare, VirtualBox, anti-virus programs, VPN programs and Intel HAXM.
> 
> Please run `keybase log send` to report the error.

My log send error ID is:
`b383f7c0128b9bfea039bf1c`
And I tried again today, log from that:
`060709277863e47e525b001c`

Running `kextstat` only returns `com.apple.xxxx` - i.e. I'm not running any other VMs or anything.

I've tried uninstalling and reinstalling the client 5 or 6 times, restarting, etc, and it's the same output every time.

If it makes any difference, I do see the /keybase root folder, but my user doesn't have permissions for it. On chmod-ing it, it's just empty.

Any help would be greatly appreciated!
Thanks!

**Comment by strib** [comment]
You're getting an authentication-related error code when trying to load the kext: -603946995

It's the same error code reported in other issues like #12720 and #13352.

A user reported one possible fix here: https://github.com/keybase/client/issues/13352#issuecomment-432856958

Another issue we've seen is that clicking the Allow button does nothing when you're using certain accessories to do the clicking, like the Apple trackpad: https://github.com/keybase/client/issues/11763#issuecomment-410790612
(Though in that case, the error code was different.)

**Comment by danielbressan** [comment]
@strib Thanks for the reply.

I just tried https://github.com/keybase/client/issues/13352#issuecomment-432856958 (adding Keybase application to the approved privacy list) and unfortunately, same behavior. 

Is there any way to get the "Allow" to show up again? It's like the machine remembers the keybase app after removing it, because in subsequent installs, it's never showed up other than the very first time. Any chance there's a 'clean' uninstall package that can be run for keybase (other than just manual clean up and trashing the application)?

**Comment by strib** [comment]
You can try this:

```sh
keybase uninstall -c redirector,fuse
```

and then restart the Keybase app and try to re-enable the Finder integration.  I don't know enough about the macOS side of things to know if that will make the Allow button re-appear.  Let me know!

**Comment by strib** [comment]
Bummer.  Other than fully disabling these security protections (via `spctl` I think, as described [here](http://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/) or `csrutil` as described [here](https://support.studionetworksolutions.com/hc/en-us/articles/115003839246-How-to-disable-Systems-Integrity-Protection-SIP-in-macOS)), I'm out of ideas.  Maybe the latter link has the best chance of working well in your case?

**Comment by danielbressan** [comment]
@strib Just an update. 

I then tried the first link (http://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/) which changed nothing for me. 

I tried the second link (https://support.studionetworksolutions.com/hc/en-us/articles/115003839246-How-to-disable-Systems-Integrity-Protection-SIP-in-macOS) It DOES work while csrutil is disabled! But after I install keybase, see it's working, then try to reenable csrutil like the article suggests, it doesn't work any more. That tells me I must have gotten my machine into a weird place with the macOS "Systems Integrity Protection (SIP)". I'm guessing keybase needs to re-request the allow permissions; and either it's not, or the OS isn't allowing it...

After some searching on issues with SIP, I'm guessing this might be a permissions issue. Since Apple removed the ability to fix permissions, I'll have to wait till the next official update to see if it fixes it (or upgrade to 10.14). I'll update here when/if that fixes anything.

**Comment by Timshel** [comment]
Putting it here since it might help :

I'm on High Sierra too and I had a problem with the `allow` button never appearing in `Security & Privacy`.

The only solution I found was to give consent using the command line in recovery mode :
```bash
spct kext-consent add 99229SGT5K
```

To find the TeamIdentifier you can run : 
```bash
codesign -dv  --verbose=4 /Applications/Keybase.app
```

**Comment by robrecord** [comment]
> spctl kext-consent add 99229SGT5K
On Mojave, I get the following:```spctl: failed to store new configuration.```

**Comment by Nezteb** [comment]
I had this same issue for a while and decided to download the latest version of Keybase.

```
$ keybase version
Client:  3.2.2-20190412030505+5262f90fd9
Service: 3.2.2-20190412030505+5262f90fd9
```

Now everything seems to be working:
<img width="1453" alt="Screen Shot 2019-04-28 at 4 38 35 PM" src="https://user-images.githubusercontent.com/3588798/56870396-6893a300-69d4-11e9-9197-23c46d082705.png">

In the event of future issues I have a bash function:
```
fixfuse() {
	echo "Loaded device drivers containing 'fuse' or 'fs':"
	sudo kextstat | grep fuse
	sudo kextstat | grep fs
	sudo kextunload -b com.github.osxfuse.filesystems.osxfusefs
	sudo kextunload -b com.github.osxfuse.filesystems.osxfuse
	sudo kextunload -b com.intel.kext.intelhaxm
	sudo kextunload -b com.github.kbfuse.filesystems.kbfuse
	sudo kextunload -b com.apple.filesystems.smbfs
	sudo kextunload -b com.paragon-software.filesystems.ntfs
}
```

**Comment by danielbressan** [comment]
I had tried all of the above, nothing worked for me. I finally did update to Mojave, and it worked! So I'm guessing it was just a broken permission thing for me that got fixed in the 'official' update process since you can't fix permissions manually anymore.

> After some searching on issues with SIP, I'm guessing this might be a permissions issue. Since Apple removed the ability to fix permissions, I'll have to wait till the next official update to see if it fixes it (or upgrade to 10.14). I'll update here when/if that fixes anything.

I'm going to call this one closed from my perspective.

**Comment by examachine** [comment]
On High Sierra, latest version still doesn't work. With latest macfuse 4.1.2. Nothing seems to work. High Sierra doesn't even seem to be supported:
$ ls -al
total 0
drwxr-xr-x@ 6 root  wheel  192 Feb  2 22:25 .
drwxr-xr-x@ 7 root  wheel  224 Feb  2 22:25 ..
drwxr-xr-x@ 3 root  wheel   96 Feb  2 22:25 10.14
lrwxr-xr-x  1 root  wheel    5 Feb  2 22:25 10.15 -> 10.14
lrwxr-xr-x  1 root  wheel    2 Feb  2 22:25 10.16 -> 11
drwxr-xr-x@ 3 root  wheel   96 Feb  2 22:25 11
