### ISSUE TITLE
windows client: change download location

### ISSUE THREAD

**Issue by shadow87qft** [keybase/client#16443]
maybe i'm blind or too stupid to find the option, but is there any way to change the default download location for files downloaded from the chat via dhe download button?
by default those files get downloaded to c:\users\[username]\downloads. 
the fact that i moved my downloads folder to a different location gets ignored.

it would be nice if i could set a custom download path so the files get downloaded directly into my veracrypt drive instead of the system default download location

**Comment by neildrichards** [comment]
Recently, when I'm downloading files, they are now being downloaded to the C:\Users\[username]\AppData\Local\Keybase\Downloads folder. I haven't moved/changed my Downloads folder, and if I click the Downloads folder icon, it still takes me to C:\Users\[username]\Downloads. Any idea what is going on?

I'm using v 4.6.1.0

**Comment by songgao** [comment]
> Recently, when I'm downloading files, they are now being downloaded to the C:\Users[username]\AppData\Local\Keybase\Downloads folder. I haven't moved/changed my Downloads folder, and if I click the Downloads folder icon, it still takes me to C:\Users[username]\Downloads. Any idea what is going on?
> 
> I'm using v 4.6.1.0

Sorry about that. We've fixed this in master. Should be back to your Downloads folder in the next release, which hopefully happens in a few days.

**Comment by vincentscode** [comment]
I'm using client version 5.1.1 and the same issue still occurs to me.
My download path is K:/ but the downloaded files and images are still put into C:\Users\[my-username]\Downloads.

Any update on this?

**Comment by ciscoheat** [comment]
This is also an issue for me, I'm using a partition snapshot software so any files downloaded to C: will pollute that snapshot. My download folder is on another drive, so changing that is essential for my work.

**Comment by vRobM** [comment]
Has this seriously not been fixed?
What do we have to do to be able to set a proper download location from within our Settings menu?

**Comment by Ferdish** [comment]
It's almost six years after @shadow87qft made a request to solve this issue and still nothing? What the heck were you devs doing all this time???
