### ISSUE TITLE
Unable to show Files in File Explorer option on Linux

### ISSUE THREAD

**Issue by kaerumy** [keybase/client#17098]
Ubuntu Linux 19.04. This feature used to work fine, now clicking on it opens a dialog "Enable Keybase in File Explorer" but clicking on Yes Enable button does nothing. As in, it doesn't seem to be accepting any input.

![image](https://user-images.githubusercontent.com/1060743/56512180-36f88300-6561-11e9-9e30-a9006f7b2aad.png)

kbfs use mount works fine though, and I can navigate and browse the mountpoint via Nautilus and CLI. 

my log id: 489e5b98b25a037dce1f951c

**Comment by strib** [comment]
That option is not supposed to show up for Linux, where the explorer integration is always enabled.

cc: @jzila @songgao I see this on the admin build too, seems like a regression.

**Comment by jzila** [comment]
Definitely a regression. We'll take a look, thanks.

**Comment by thwaller** [comment]
Same problem here. Clicking "Yes, Enable" does nothing.
Ubuntu 18.04.2

**Comment by eli-schwartz** [comment]
I get this dialog too, but sometimes I also get the message:

> Error: /keybase is unavailable. Please try again. at mo.a.readdir (file:///usr/share/keybase-app/desktop/dist/main.bundle.js:1:2982507) at FSReqWrap.oncomplete (fs.js:141:20)

So clicking the button seems to be doing something. Unsure if it is related or just coincidental. But I do not have the setuid redirector running.

**Comment by Fantoni0** [comment]
Same problem here. Clicking "Yes, Enable" does nothing.
Ubuntu 18.010
It worked flawlessly until a few weeks ago when I restarted the computer.

**Comment by songgao** [comment]
Thanks folks; we'll have a fix soon and let you all know when we have a testable version.

**Comment by songgao** [comment]
Hey folks, we have the fix merged: https://github.com/keybase/client/pull/17236

It should be included in the next release but if you feel adventurous the [nightly build](https://keybase.io/docs/linux-user-guide#nightly-builds) should already have it.

**Comment by zensir** [comment]
Still getting this error too.
elementaryOs Odin, Built on Ubuntu 20.04.3 LTS
When I click on "Show in File Explorer" it opens Blender and closes.
