### ISSUE TITLE
Keybase Mac does not go into hiding

### ISSUE THREAD

**Issue by bbaassssiiee** [keybase/client#17823]
Keybase GUI Version: 4.0.0-20190507193726+6614a49937

When I have the chat window open and another app has focus, pressing CMD+ALT+H (Hide Others) does not hide the Keybase window.

When I have the chat window open and the Keybase app has focus, pressing CMD+H (Hide Keybase) does not hide the Keybase window.

**Comment by arunsathiya** [comment]
I use a macro on Keyboard Maestro to hide all apps. I can confirm the same behavior as reported.

Keybase app doesn't hide.

**Comment by adraffy** [comment]
I also have this problem: macOS (10.15, 19A602) + Keybase (4.6.0).

**Comment by adraffy** [comment]
I believe this issue has been fixed in 4.70?

**Comment by arunsathiya** [comment]
Does not seem to be the case for me. Keybase still doesn't go into hiding, I am on 4.7.2.

**Comment by adraffy** [comment]
@arunsathiya which macOS?

**Comment by arunsathiya** [comment]
Catalina, 10.15.1.

**Comment by adraffy** [comment]
My Keybase no longer hides again (10.15.1, 19B88) and Keybase (4.7.2).

"About Keybase" window hides normally, just not the main window.

**Comment by donatj** [comment]
Gif of the issue in action:

![Screen Capture on 2019-11-11 at 10-03-33 opt](https://user-images.githubusercontent.com/133747/68601879-db450700-046a-11ea-8a72-e3ea9bcd32b6.gif)

**Comment by bbaassssiiee** [comment]
Fixed, thanks!

**Comment by adraffy** [comment]
Hide is broken again (10.15.2) with Keybase (5.1.1).

Another report: https://github.com/keybase/client/issues/21843
