### ISSUE TITLE
Wallet not loading on Windows PC or Android App

### ISSUE THREAD

**Issue by hankified** [keybase/client#24285]

**Comment by mimart0** [comment]
having the same issue

**Comment by ufoundtom** [comment]
Same issue across all devices Windows, Apple, and Android.

**Comment by damian-pastorini** [comment]
same here

**Comment by sebbrandt87** [comment]
Same for me after a small transaction :(

**Comment by Onkovat** [comment]
Wait, Keybase is dead since this is not solved yet? Can I import my wallet elsewhere? Have the circles going on endlessly on android app and desktop. So server is off?

**Comment by damian-pastorini** [comment]
Same here: https://github.com/keybase/client/issues/24290
Was this fixed or anyone was able to finally access?

**Comment by Bonsailinse** [comment]
Same problem, not being able to access the wallet is not acceptable.
To make things worse we don't even get a response here.

**Comment by chindraba-work** [comment]
Can't find it now, but iirc there was an issue with Stellar changing their protocol and the devs here are now busy with Zoom. If, you saved the secret key somewhere it is still usable through other stellar-aware apps, which have updated their system to match the Stellar changes.

**Comment by sebbrandt87** [comment]
For me it was solved after some hours. Don't panic and try again later.

**Comment by damian-pastorini** [comment]
@sebbrandt87 this is since August...

**Comment by damian-pastorini** [comment]
For everyone that's still unable to access your wallets maybe this helps:
- Open Keybase App (Windows in my case).
- Go to the chats and if you check the SpaceDrop chat it will probably look like if you don't have access (like if you were not in the group). Unfortunately I didn't took any screenshots of it.
- At that point you will see that parts of the chats related to the spacedrop values giving to you are going to keep loading (like in the wallet).
- Click on the spacedrop account and at some point you will get redirected to https://keybase.io/team/airdrop (I didn't seems to be related but I've joined the group).
- Then included a new verification on my account (I didn't have Twitter so I've verified that).
- After all these I went back to the spacedrop chat and suddenly the wallets references started to work and from there the wallet went back to normal and now I can access.

I know this all looks weird and unrelated but maybe some of these actions made some change on my account re-validate the wallet data and that make it work again, so dropping here my actions and maybe someone else have the same luck.

That been said, for sure the issue is still there and should be fixed.

**Comment by Bonsailinse** [comment]
> For me it was solved after some hours. Don't panic and try again later.

It's not about panicking, it's about not having access to my money when I want to. I wanted to trade a fair amount of lumen and could not send them because I trusted keybase with managing them.

Also not getting any developer response is excusable in some parts, not in the one where actual money is involved.

**Comment by chindraba-work** [comment]
FWIW the addition of Stellar/Lumen to Keybase was accompanied with a warning that it was experimental, or some such. Keeping a backup of the account's secret key was advised, and somewhere there were steps on how to do just that.

I would highly recommend that the secret key be exported as soon as you are again able to access it. At this time all of my accounts are accessible, without doing anything special.

I won't bother to recommend a different wallet to use as a secondary, or primary if you've decided to abandon the KB wallet. As in any other online/app framework, important data should be saved outside of the system somewhere.

**Comment by Bonsailinse** [comment]
I have the wallet backed up so I'm not afraid of losing access completely, I just didn't have access to the backup device at that time.
I will move my funds to a different wallet and just abandon this feature of keybase completely, I don't need an experimental feature if it gets no attention of the developer.

Thanks for your aid and have a nice day.
