### ISSUE TITLE
Fedora 35 Package signature failing

### ISSUE THREAD

**Issue by vvro** [keybase/client#24775]
GPG key at https://keybase.io/docs/server_security/code_signing_key.asc (0x656D16C7) is already installed
The GPG keys listed for the "keybase" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: keybase-5.9.0.20211217212642.29bfd9d39f-1.x86_64

**Comment by ich199** [comment]
probably the same issue as https://github.com/keybase/client/issues/24637

**Comment by timfallmk** [comment]
Probably related to #24741 as well. Looks like there are signature issues all over the place.

**Comment by heronhaye** [comment]
Hi, we believe we have fixed this issue. Please try upgrading Keybase. Thank you.

**Comment by ardrigh** [comment]
> Hi, we believe we have fixed this issue. Please try upgrading Keybase. Thank you.

@heronhaye I am still getting this error message in Fedora 35 today with the latest package. I don't believe this is resolved.

Also, looking at this page https://book.keybase.io/docs/server/our-code-signing-key  shows a different key than the one linked in the repo file here https://keybase.io/docs/server_security/code_signing_key.asc

Which key is the correct one the RPM file should be signed with?

**Comment by heronhaye** [comment]
@ardrigh Did you try either reinstalling or removing the existing key as described in https://github.com/keybase/client/releases/tag/v5.9.1?

Good question, it is the same public key but the one in the file has some expired cross-signatures removed. We're working on updating the other location as well.

**Comment by ardrigh** [comment]
> @ardrigh Did you try either reinstalling or removing the existing key as described in https://github.com/keybase/client/releases/tag/v5.9.1?

Sorry I didn't see that update as Fedora is only showing 5.9.0 package. I have removed the key and the package has installed fine now thanks.
