### ISSUE TITLE
Windows - Keybase client crashed when started copying large file ~400MB

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2755]
I tried copying a zip file to keybase from a remote drive, keybase client immediately crashed and shows below error 
![keybase_crash_windows_large_file_400mb](https://cloud.githubusercontent.com/assets/27522/14976746/a41c4b38-110e-11e6-8b3c-4afce0afcbd6.png)

I tried copying the same file to keybase from my linux keybase client, there too keybase crashed

Log id :  c730ad738559a7aaa36b661c

**Comment by strib** [comment]
I don't see anything weird in the kbfs log.  @zanderz @taruti, any idea what this means?

Of course, our Windows client is not in great shape right now, so you might want to retry this test when we put the next release up, which contains a ton of fixes.

**Comment by taruti** [comment]
@sirishkumar "I tried copying the same file to keybase from my linux keybase client, there too keybase crashed"

Can you confirm that you have the crash on Linux too?

**Comment by strib** [comment]
Ah, I missed that part.  @sirishkumar please `log send` the Linux logs too, if you can.  There are known bugs where if you try to write more than 5 MB of data at once, it will appear to hang your file system for long periods of time.  I didn't see evidence of this in your Windows KBFS log though.

**Comment by zanderz** [comment]
A new version with many improvements was released today - please either download or issue the `keybase update check` command. Thanks!

**Comment by sirishkumar** [comment]
I have tried again on my Ubuntu machine after running "keybase update check and keybase update run".  I was on the latest version and I see same error again.

![keybase_crash_ubuntu](https://cloud.githubusercontent.com/assets/27522/15005270/b7e53e7c-11c2-11e6-8966-113fab5a3987.png)

Log Id : 3a0ea01718ce62affc96ff1c

**Comment by strib** [comment]
Thanks!  Looks like an out-of-memory error.  That's unexpected. We'll try to reproduce it.

**Comment by cjb** [comment]
FWIW, keybase update run doesn't do anything on Ubuntu. Need to use apt-get.

**Comment by sirishkumar** [comment]
@cjb I didnt know that. I have updated the kaybase now and retried .  Same error is reproduced again.

**Log Id** : a93de7bfe317863e972d3a1c

**Version Details**
Client:  1.0.15-20160503160057+13ae9cc
Service: 1.0.15-20160503160057+13ae9cc

**Comment by jzila** [comment]
Please try the latest version of keybase on Ubuntu. This bug should be fixed now.

**Comment by taruti** [comment]
@jzila it still exists on Windows. This and #2825 are about the same issue related to large truncates before writes.

**Comment by strib** [comment]
@taru: @jzila is talking about the out-of-memory crash, which is very different from a timeout due to big files.

**Comment by taruti** [comment]
@strib, ok. It will fail with the truncate issue probably sometimes too. Managed to reproduce that with a large file copy today.

**Comment by jzila** [comment]
@sirishkumar could you please check whether the new Ubuntu client is working for you now? I think we've fixed this bug, just wanted to make sure.

**Comment by jzila** [comment]
I'm closing this for now. Please reopen if this issue persists.

**Comment by sirishkumar** [comment]
I tried copying 200MB 7z file on windows. It failed

Logs : 7bc3bec0dae865807fa5eb1c

**Comment by strib** [comment]
Hi @sirishkumar -- this one is a known Windows issue (where the kernel issues a large truncate before writing the file, and KBFS doesn't handle it fast enough).  We're already working on it internally.  Thanks for the report!
