### ISSUE TITLE
Unable to prove Reddit identity

### ISSUE THREAD

**Issue by CapraRoyale** [keybase/client#5107]
Keybase GUI Version: 1.0.18-20161116112520+95f8303
Windows 10 Pro

Click "Prove your Reddit"
Enter username
Click "Reddit form"
Nothing

**Comment by triptolemoose** [comment]
Same issue when trying to verify on iPhone both when launching Reddit app and in safari.

**Comment by malgorithms** [comment]
@CapraRoyale  - can you confirm this is fixed now? (and close issue if so). thanks!

**Comment by CapraRoyale** [comment]
It seems to have resolved on it's own.

**Comment by KainerW** [comment]
No. it is still there and it wont allow to prove on reddit on iOS. Bug. From 2017 not fixed today. laughable.
