### ISSUE TITLE
Systray icon is impossible to make out

### ISSUE THREAD

**Issue by wolfbeast** [keybase/client#5730]
Keybase GUI Version: 1.0.18-20170207061119+ce0f90d

With your latest update and change of icon from the weasel head to... I don't even know what it is now, the systray icon has become an impossible to make out black/white blurb on Windows.
(OS: Win 7 x64)

If I may make a suggestion: you should have stuck with what you had previously - it's recognizable.

**Comment by zanderz** [comment]
@cecileboucheron Default background is light on Win7

**Comment by cecileboucheron** [comment]
That'll be fixed in the next couple days. Thanks!

**Comment by wolfbeast** [comment]
FYI: this is still an issue in Keybase GUI Version: 1.0.18-20170223121400+af0e640
I also noticed the same monochrome icon is visible in the taskbar when the systray pop-up is visible. The main window, when opened, has a proper task icon (although I'm still in the dark as to what it is supposed to represent).
![keybase1](https://cloud.githubusercontent.com/assets/3359132/23341017/954bb8be-fc40-11e6-9162-f9086bec4cbf.png)
