### ISSUE TITLE
App seems to be stuck, infinitely loading

### ISSUE THREAD

**Issue by DoctorKrieger** [keybase/client#6687]
Keybase GUI Version: 1.0.21-20170413113755+766e240

Whenever I launch the app, it never seems to get further than the loading screen.

**Comment by FullofQuarks** [comment]
I too am experiencing this issue. GUI version: 1.0.21+20170413113438+766e240

Started experiencing this issue within the past couple of days. Uninstalls/Reinstalls have not fixed this issue. GUI screen sits on "Loading...". I've logged in via the shell, and the system tray icon shows my folders, but will not let me open them. KBFS drive does not show up either.

**Comment by erikthered** [comment]
I'm having this issue as well. As with @FullofQuarks I am also able to login from the shell, but the desktop app is still stuck on "Loading..."

I'm on Windows 10.

**Comment by maxtaco** [comment]
Can you guys all `keybase log send`? 

IS everyone on Windows?

CC: @zanderz

**Comment by erikthered** [comment]
My desktop client actually started working after I rebooted. I'll send logs if it occurs again.

**Comment by CameronBanga** [comment]
I'm seeing this same issue, but on Android right now, on a rooted Nexus 4, running 5.1.1. Won't go past this screen. Not sure if there's a way to sent logs from this sort of page on Android?: 

![android_screen_20170425-195158](https://cloud.githubusercontent.com/assets/611354/25413527/a9e10170-29f0-11e7-9415-42b59c2760c3.png)

**Comment by JeanlucFranklin** [comment]
I was having the same issue as @CameronBanga above me on mobile 
Device Model: Nexus 6
Android Version: 6.0.1
Rooted: Yes
CyanogenMod Version: 13.0-20161030-NIGHTLY-shamu. 
Keybase Version ( I believe ): 1.0.21-20170425210214+9f2981d9b
--
When I launch the app it briefly shows the key splash screen, and then the loading screen. To where it sits forever until the phone screen times out and then when I relaunch it gives me a notification that it lost connectivity, or I did.
I still got notifications in my notification bar about when people messaged me on keybase suggesting it was running in the background.

I dug around to see if I could find a log file, however I didn't see any so I packaged the app back up hopefully I grabbed everything. And I reinstalled the keybase mobile app, from there it started right up without issue. I will note that when I first installed it, that it worked just fine as well for about a day, and then suddenly infinite loading screens.

**Comment by CameronBanga** [comment]
I should note that on my install, I did get past this screen once. I was in the app, and it worked fine as well. I used it for about an hour, then can't remember what happened, a crash or something, and I got this screen and couldn't get past it.

**Comment by maxtaco** [comment]
@CameronBanga it would be great to see your log send... If you can get to the feedback window after a successful start of the app, please send feedback. Thanks for your help!

Cc: @chrisnojima on android being stuck in the loading screen

**Comment by sleibrock** [comment]
Getting the same issue as well on Windows.

Log ID: f31cb76be01b5d5c21327d1c

Client loads up but can't access anything.

**Comment by Thewest123** [comment]
I have the simmilar problem. After reinstallation, it works until next reboot. Then I have infinite loading. 
Log ID: 8c5a2b88719fa49a69182a1c (Hope it helps)

**Comment by zanderz** [comment]
For those of you on Windows, two users experiencing this disconnected
message had it solved with the fix contained in this special build, if you
would like to try:
https://s3.amazonaws.com/prerelease.keybase.io/windows/Keybase_1.0.21-20170428134902%2B4280d08.386.exe

**Comment by jsb2092** [comment]
This fixed my issue - so far

**Comment by Thewest123** [comment]
I still have the problem, even with the special build. :/
Log ID, if it helps: 35188c831ad3f903299ebe1c

**Comment by zanderz** [comment]
@Thewest123 Your logs suggest the Keybase service is not being started when you reboot. Could you take a look and see if:
- TaskManager shows any lower-case `keybase.exe` running
- you have a link called KeybaseStartup in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup`
- if your app comes back to normal if you launch that link
- you have any AV programs that may be blocking our utilities
Thanks for the report.

**Comment by jsb2092** [comment]
@zanderz I just wanted to know that you've been very helpful.  More info from me though.  I am not running any 3rd party AV, and the fact that I can start it manually seems odd (not being blocked by anything).  I am running build 16188 of win10.

**Comment by chrisnojima** [comment]
@CameronBanga you could hook up your phone to your computer and look at the android logs possibly (if you can't get to the log send page). Like download android studio (https://developer.android.com/studio/index.html) and look at the Android Monitor/logcat to see the logs

**Comment by Thewest123** [comment]
@zanderz Thank you, sir! Everything now works fine. :)

**Comment by zanderz** [comment]
@Thewest123 Did something specific help, or did it just start working spontaneously? It may help a few users who are stuck still.

**Comment by CameronBanga** [comment]
@chrisnojima Took a look over weekend, but couldn't recreate. I don't use Android day to day, so was on a secondary device a couple weeks back. I'll try again this week and if I can get logs, will post here.

**Comment by chrisnojima** [comment]
@CameronBanga if you can use keybase chat on a desktop thats likely the best way to transmit them to me (vs here publicly)
