### ISSUE TITLE
git push --force always fails with an error

### ISSUE THREAD

**Issue by coderjoe** [keybase/client#8912]
If you push a branch, then try and correct the push by using `git push --force` keybase will initialize, sync, and then (almost) always error with `error: failed to push some refs to 'keybase://private/username/repository.git'.

The linked text file is a bash script which I used to reproduce the problem. Please note that it presumes you don't already have a repository named `forcepushbugtest`. It also sleeps for a few seconds before the final push since it seems to make the problem easier to reproduce. When the script was force pushing too quickly I found that it would occasionally succeed. This is why I note it almost always errors. When pushing faster than any human would, it occasionally succeeds, but I've never experienced success in my real repositories.

[keybase-git-force-push-bug.txt](https://github.com/keybase/client/files/1366698/keybase-git-force-push-bug.txt)

**Comment by dabura667** [comment]
I just ran your script. Everything worked fine.

**Comment by dabura667** [comment]
What is your keybase version and git version?

**Comment by dabura667** [comment]
For me:

git version 2.7.4
keybase version 1.0.34-20171006165932+d0664a9cb

**Comment by coderjoe** [comment]
Would you mind trying a few more times? Maybe increase the `sleep 5`? I did have to add a sleep command to the script to get it to happen more often. Maybe there's a chance there isn't sufficient wait time on your machine? Then again it could be completely unrelated..

Versions:

```
coderjoe@localhost:/tmp% keybase version
Client:  1.0.34-20171006165932+d0664a9cb
Service: 1.0.34-20171006165932+d0664a9cb
coderjoe@localhost:/tmp% git --version
git version 2.7.4
```
My most recent run as of this morning:

```
coderjoe@localhost:/tmp% ./keybase-git-force-push-bug.sh 
Repo deleted!
Repo created! You can clone it with:
  git clone keybase://private/coderjoe/forcepushbugtest
keybase://private/coderjoe/forcepushbugtest.git
Cloning into 'forcepushbugtest'...
Initializing Keybase... done.
Syncing with Keybase... done.
Syncing encrypted data to Keybase: (100.00%) 2.72/2.72 KB... done.
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[master (root-commit) c796dc1] First commit
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt
Initializing Keybase... done.
Syncing with Keybase... done.
Counting and decrypting: 3 objects... done.
Preparing and encrypting: (100.00%) 3/3 objects... done.
Indexing hashes: (100.00%) 3/3 objects... done.
Indexing CRCs: (100.00%) 3/3 objects... done.
Indexing offsets: (100.00%) 3/3 objects... done.
To keybase://private/coderjoe/forcepushbugtest.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
[master 946f927] Second commit
 1 file changed, 1 insertion(+)
[master 225b003] Third commit
 1 file changed, 1 insertion(+)
Initializing Keybase... done.
Syncing with Keybase... done.
Counting and decrypting: 6 objects... done.
Preparing and encrypting: (100.00%) 6/6 objects... done.
Indexing hashes: (100.00%) 6/6 objects... done.
Indexing CRCs: (100.00%) 6/6 objects... done.
Indexing offsets: (100.00%) 6/6 objects... done.
To keybase://private/coderjoe/forcepushbugtest.git
   c796dc1..225b003  master -> master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 946f927 Second commit
Initializing Keybase... done.
Syncing with Keybase... done.
error: failed to push some refs to 'keybase://private/coderjoe/forcepushbugtest.git'
```

**Comment by strib** [comment]
@coderjoe: I just tested this several times myself, with different timeouts, and I couldn't repro either.  We tested force push quite a bit before release, so I'd be pretty surprised if it was universally broken.  

That said, it looks like it's broken in your environment for some reason.  To figure out why, I'd need to look at logs.  Can you please do a `keybase log send` and let us know the resulting ID so I can take a look at what's happening for you?

**Comment by coderjoe** [comment]
Log: 5db2f8a0643a087ed402d81c

**Comment by coderjoe** [comment]
As an aside is there a way for me to audit the content of these logs?

**Comment by strib** [comment]
You can run `keybase status` which will show you the location of the log files we send, and then you can check those files.  I'll take a look at the logs.

**Comment by strib** [comment]
Hmm, you are consistently able to repro a panic in our code, shown in your `keybase.git.log`.  I'll have to take a look at the code more carefully when I get more time, either later today or tomorrow.  Sorry for the bad experience!  Will fix ASAP.

**Comment by coderjoe** [comment]
Not a problem. For now I got around the problem by deleting the repository and re-creating it. Good luck! This seems like it'll be difficult to debug.

**Comment by strib** [comment]
@coderjoe: found the problem and pushed a merge to master, should be fixed in the next release.  Thanks!

**Comment by coderjoe** [comment]
Fantastic to hear. I'm glad it wasn't a wild goose chase! Thanks for your help. I can't wait. :)

**Comment by M-Pixel** [comment]
Still experiencing this in the latest version of Keybase: 67559eff096c95d76370e61c

**Comment by strib** [comment]
@M-Pixel I don't see any errors in the logs you sent.  Can you share the actual output of a failed git command with me, and then do another log send right you get the error?

**Comment by M-Pixel** [comment]
Git Output:
```
C:\REDACTED> git.exe push --porcelain --progress --force-with-lease --recurse-submodules=check origin refs/heads/master:refs/heads/master
Initializing Keybase... done.
Syncing with Keybase... done.
Preparing and encrypting: (0.00%) 0/7 objects... (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Indexing hashes: (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Indexing CRCs: (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Indexing offsets: (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Syncing encrypted data to Keybase: (0.00%) 0.00/18.25 KB... (100.00%) 18.25/18.25 KB... done.
To keybase://team/REDACTED/REDACTED
failed to push some refs to 'keybase://team/REDACTED/REDACTED'
! refs/heads/master:refs/heads/master [remote rejected] (some refs were not updated)
Done
'master' rejected (non-fast-forward)
Initializing Keybase... done.
Syncing with Keybase... done.
Preparing and encrypting: (0.00%) 0/7 objects... (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Indexing hashes: (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Indexing CRCs: (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Indexing offsets: (0.00%) 0/7 objects... (14.29%) 1/7 objects... (28.57%) 2/7 objects... (42.86%) 3/7 objects... (57.14%) 4/7 objects... (71.43%) 5/7 objects... (85.71%) 6/7 objects... (100.00%) 7/7 objects... done.
Syncing encrypted data to Keybase: (0.00%) 0.00/18.25 KB... (100.00%) 18.25/18.25 KB... done.
error: failed to push some refs to 'keybase://team/REDACTED/REDACTED'
```

New Logs: `53559c16f9bffc1bf78adf1c`

**Comment by keybase-travis** [comment]
This might just be a git conflict.  Try pulling first.

**Comment by maxtaco** [comment]
Oh whoops. I see now you are forcing.

**Comment by strib** [comment]
@M-Pixel you are using `--force-with-lease`, not `--force`, as in the original issue.  We don't support `--force-with-lease` because the git remote protocol doesn't pass that option to us.  Same issue as #9981.  Sorry!  Let me know if `--force` by itself doesn't work.

**Comment by M-Pixel** [comment]
Thanks for clarifying.  I'm using SmartGit - apparently it uses `--force-with-lease` under the hood for its "force" GUI option.

**Comment by coderjoe** [comment]
This is now quite a few years old with no action on it. I no longer use or can reproduce the original issue. Any objections to closing as "won't fix"?

**Comment by coderjoe** [comment]
Closing due to lack of reproduction and because there was no objection above.
